[Phase1]
# virustotal = true
avclass = true
# capa = true
# floss = true
exiftool = true
file = true
# strings = true
md5sum = true
sha256sum = true
# xxd = true
yara = true
imphash = true
rabin2 = true

[Phase3]
windows.pslist.PsList = true
windows.malfind.Malfind,pid,args,--dump-dir malfind_dumps = true
windows.cmdline.CmdLine,pid = true
windows.dlllist.DllList,pid = true
windows.handles.Handles,pid = true

